server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: 1357123aA!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create  # 프로젝트를 실행할때마다 테이블을 어떻게 할지 결정!!
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 네이밍 전략
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false # jpa 가 사용하는 기본 넘버링 전략을 따라가지 않는다!
#    show-sql: true # sql 이 보이게
#    properties:
#      hibernate.format_sql: true #sql문이 예쁘게 정렬되서 보이게

  jackson:
    serialization:
      fail-on-empty-beans: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  profiles:
    include: oauth
  # 정의!!!
  # cos:
  #  key: ~~~
  #  client-id: ~~~~



